/* ==========================================================================
   NETFLIX MOVIE DATABASE (js/data.js)
   Centralized database of sample titles with metadata, genres, & media URLs.
   ========================================================================== */

const moviesData = [
  {
    id: 'interstellar',
    title: 'SpiderMan Homecoming',
    originalTitle: 'Interstellar',
    type: 'movie',
    year: 2026,
    rating: 8.9,
    maturity: '13+',
    duration: '2h 49m',
    badge: 'TOP 10',
    match: '99% Match',
    genre: ['Sci-Fi', 'Adventure', 'Drama'],
    description: 'A mysterious signal from beyond the galaxy changes the future of humanity as explorers travel through a wormhole.',
    synopsis: 'In a future where Earth is dying, the last hope lies beyond the stars. A team of astronauts leads a desperate mission through a newly discovered wormhole in search of a habitable new home.',
    cast: ['Matthew McConaughey', 'Anne Hathaway', 'Jessica Chastain'],
    director: 'Christopher Nolan',
    poster: 'assets/images/spiderman.jfif',
    backdrop: 'assets/images/bgmain.jpeg',
    posterFallback: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=600&auto=format&fit=crop&q=80',
    backdropFallback: 'https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?w=1600&auto=format&fit=crop&q=80',

    // FIXED: YouTube watch/short URL changed to embed URL
    trailerUrl: 'https://www.youtube.com/embed/rk-dF1lIbIg',

    movieUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    categories: ['trending', 'popularMovies', 'scifi', 'topRated', 'newReleases']
  },

  {
    id: 'money-heist',
    title: 'The Grand Heist',
    originalTitle: 'Money Heist',
    type: 'tv',
    year: 2025,
    rating: 8.7,
    maturity: '18+',
    duration: '5 Seasons',
    badge: 'MUST WATCH',
    match: '97% Match',
    genre: ['Action', 'Crime', 'Thriller'],
    description: 'A brilliant criminal mastermind recruits eight thieves to execute the largest heist in modern history.',
    synopsis: 'The Professor leads an elite crew in a high-stakes standoff against police forces while printing billions in cash inside the national mint.',
    cast: ['Álvaro Morte', 'Úrsula Corberó', 'Pedro Alonso'],
    director: 'Álex Pina',
    poster: 'assets/images/Money.jfif',
    backdrop: 'assets/images/bg2main.jpg',
    posterFallback: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&auto=format&fit=crop&q=80',
    backdropFallback: 'https://images.unsplash.com/photo-1514306191717-452ec28c7814?w=1600&auto=format&fit=crop&q=80',
    trailerUrl: 'https://www.youtube.com/embed/_InqQJRqGW4',
    movieUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    categories: ['trending', 'popularTV', 'action', 'thriller', 'continueWatching']
  },

  {
    id: 'cyberpunk-edgerunners',
    title: 'Neon Cyberpunk',
    originalTitle: 'Cyberpunk: Edgerunners',
    type: 'tv',
    year: 2024,
    rating: 8.8,
    maturity: '18+',
    duration: '1 Season',
    badge: 'ANIMATION HIT',
    match: '96% Match',
    genre: ['Sci-Fi', 'Action', 'Animation'],
    description: 'A street kid trying to survive in a technology and body-modification obsessed city of the future.',
    synopsis: 'Having lost everything in a drive-by shooting, David Martinez chooses to stay alive by becoming an edgerunner—a mercenary outlaw.',
    cast: ['KENN', 'Aoi Yuuki', 'Hiroki Touchi'],
    director: 'Hiroyuki Imaishi',
    poster: 'assets/images/Onep.jfif',
    backdrop: 'assets/images/movie1.jpg',
    posterFallback: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=600&auto=format&fit=crop&q=80',
    backdropFallback: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=1600&auto=format&fit=crop&q=80',
    trailerUrl: 'https://www.youtube.com/embed/JtqIas3bYhg',
    movieUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
    categories: ['animation', 'scifi', 'action', 'popularTV', 'newReleases']
  },

  {
    id: 'the-dark-knight',
    title: 'Shadow Knight',
    originalTitle: 'The Dark Knight',
    type: 'movie',
    year: 2024,
    rating: 9.0,
    maturity: '16+',
    duration: '2h 32m',
    badge: 'MASTERPIECE',
    match: '99% Match',
    genre: ['Action', 'Crime', 'Drama'],
    description: 'When a menace known as the Joker emerges, he plunges the city into chaos and forces a vigilante to step up.',
    synopsis: 'Batman raises the stakes in his war on crime with the help of Lt. Jim Gordon and District Attorney Harvey Dent until an anarchic mastermind threatens everything.',
    cast: ['Christian Bale', 'Heath Ledger', 'Aaron Eckhart'],
    director: 'Christopher Nolan',
    poster: 'assets/images/darkknight.jfif',
    backdrop: 'assets/images/movie7.jpg',
    posterFallback: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=600&auto=format&fit=crop&q=80',
    backdropFallback: 'https://images.unsplash.com/photo-1478760329108-5c3ed9d495a0?w=1600&auto=format&fit=crop&q=80',
    trailerUrl: 'https://www.youtube.com/embed/EXeTwQWrcwY',
    movieUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    categories: ['topRated', 'popularMovies', 'action', 'drama', 'trending']
  },

  {
    id: 'stranger-things',
    title: 'Stranger Echoes',
    originalTitle: 'Stranger Things',
    type: 'tv',
    year: 2025,
    rating: 8.7,
    maturity: '16+',
    duration: '4 Seasons',
    badge: 'TOP 10',
    match: '98% Match',
    genre: ['Sci-Fi', 'Horror', 'Drama'],
    description: 'When a young boy vanishes, a small town uncovers a mystery involving secret experiments and a strange girl.',
    synopsis: 'In 1980s Indiana, a group of young friends witness supernatural forces and secret government exploits while trying to rescue their missing friend.',
    cast: ['Millie Bobby Brown', 'Finn Wolfhard', 'Winona Ryder'],
    director: 'The Duffer Brothers',
    poster: 'assets/images/stranger.jfif',
    backdrop: 'assets/images/silentsea.jpg',
    posterFallback: 'https://images.unsplash.com/photo-1509281373149-e957c6296406?w=600&auto=format&fit=crop&q=80',
    backdropFallback: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1600&auto=format&fit=crop&q=80',
    trailerUrl: 'https://www.youtube.com/embed/b9EkMc79ZSU',
    movieUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    categories: ['trending', 'popularTV', 'horror', 'scifi', 'continueWatching']
  },

  {
    id: 'squid-game',
    title: 'The Survival Trial',
    originalTitle: 'Squid Game',
    type: 'tv',
    year: 2024,
    rating: 8.1,
    maturity: '18+',
    duration: '2 Seasons',
    badge: 'GLOBAL TRENDING',
    match: '95% Match',
    genre: ['Action', 'Thriller', 'Drama'],
    description: 'Hundreds of cash-strapped players accept a strange invitation to compete in children’s games for a high-stakes prize.',
    synopsis: 'A secret survival competition pits 456 contestants in life-or-death challenges for 45.6 billion won.',
    cast: ['Lee Jung-jae', 'Park Hae-soo', 'Wi Ha-joon'],
    director: 'Hwang Dong-hyuk',
    poster: 'assets/images/squidgame.jfif',
    backdrop: 'assets/images/movie8.jpeg',
    posterFallback: 'https://images.unsplash.com/photo-1563089145-599997674d42?w=600&auto=format&fit=crop&q=80',
    backdropFallback: 'https://images.unsplash.com/photo-1533488765986-dfa2a9939acd?w=1600&auto=format&fit=crop&q=80',
    trailerUrl: 'https://www.youtube.com/embed/oqxAJKy0ii4',
    movieUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4',
    categories: ['trending', 'thriller', 'action', 'popularTV']
  },

  {
    id: 'inception',
    title: 'Dream Realm',
    originalTitle: 'Inception',
    type: 'movie',
    year: 2023,
    rating: 8.8,
    maturity: '13+',
    duration: '2h 28m',
    badge: 'MIND BENDING',
    match: '99% Match',
    genre: ['Sci-Fi', 'Action', 'Thriller'],
    description: 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea.',
    synopsis: 'Dom Cobb is a skilled thief who enters the sub-conscious during the dream state. He receives a final chance at redemption if he can pull off inception.',
    cast: ['Leonardo DiCaprio', 'Joseph Gordon-Levitt', 'Elliot Page'],
    director: 'Christopher Nolan',
    poster: 'assets/images/inception.jfif',
    backdrop: 'assets/images/movie3.avif',
    posterFallback: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&auto=format&fit=crop&q=80',
    backdropFallback: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=1600&auto=format&fit=crop&q=80',
    trailerUrl: 'https://www.youtube.com/embed/YoHD9XEInc0',
    movieUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    categories: ['scifi', 'thriller', 'popularMovies', 'topRated']
  },

  {
    id: 'the-silent-sea',
    title: 'Lunar Silence',
    originalTitle: 'The Silent Sea',
    type: 'tv',
    year: 2025,
    rating: 7.9,
    maturity: '16+',
    duration: '1 Season',
    badge: 'SCI-FI THRILLER',
    match: '91% Match',
    genre: ['Sci-Fi', 'Horror', 'Thriller'],
    description: 'During a 24-hour mission on the moon, space explorers try to retrieve samples from an abandoned research facility.',
    synopsis: 'Set in a future Earth suffering from severe water shortage, space scientists embark on a secret mission to an abandoned lunar research base.',
    cast: ['Bae Doona', 'Gong Yoo', 'Lee Joon'],
    director: 'Choi Hang-yong',
    poster: 'assets/images/silentsea1.jfif',
    backdrop: 'assets/images/silentsea3.png',
    posterFallback: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=600&auto=format&fit=crop&q=80',
    backdropFallback: 'https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=1600&auto=format&fit=crop&q=80',
    trailerUrl: 'https://www.youtube.com/embed/Af_HjhLd3uU',
    movieUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    categories: ['scifi', 'horror', 'thriller', 'newReleases']
  },

  {
    id: 'wednesday',
    title: 'Midnight Mystery',
    originalTitle: 'Wednesday',
    type: 'tv',
    year: 2024,
    rating: 8.2,
    maturity: '13+',
    duration: '1 Season',
    badge: 'POPULAR',
    match: '96% Match',
    genre: ['Comedy', 'Horror', 'Fantasy'],
    description: 'Follows Wednesday Addams’ years as a student, attempting to master her emerging psychic ability and solve a murder mystery.',
    synopsis: 'A sleuthing, supernaturally infused mystery charting Wednesday Addams’ years as a student at Nevermore Academy.',
    cast: ['Jenna Ortega', 'Gwendoline Christie', 'Riki Lindhome'],
    director: 'Tim Burton',
    poster: 'assets/images/wednesday.jfif',
    backdrop: 'assets/images/bgmain.jpeg',
    posterFallback: 'https://images.unsplash.com/photo-1509281373149-e957c6296406?w=600&auto=format&fit=crop&q=80',
    backdropFallback: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1600&auto=format&fit=crop&q=80',
    trailerUrl: 'https://www.youtube.com/embed/Q73UhUTs6y0',
    movieUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
    categories: ['comedy', 'horror', 'family', 'popularTV']
  },

  {
    id: 'blade-runner-2049',
    title: 'Neon Odyssey 2049',
    originalTitle: 'Blade Runner 2049',
    type: 'movie',
    year: 2024,
    rating: 8.4,
    maturity: '16+',
    duration: '2h 44m',
    badge: 'VISUAL FEAST',
    match: '95% Match',
    genre: ['Sci-Fi', 'Action', 'Drama'],
    description: 'Young Blade Runner K’s discovery of a long-buried secret leads him to track down former Blade Runner Rick Deckard.',
    synopsis: 'Thirty years after the events of the first film, a new blade runner unearths a secret that could plunge what remains of society into chaos.',
    cast: ['Ryan Gosling', 'Harrison Ford', 'Ana de Armas'],
    director: 'Denis Villeneuve',
    poster: 'assets/images/2049.jfif',
    backdrop: 'assets/images/bg2main.jpg',
    posterFallback: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=600&auto=format&fit=crop&q=80',
    backdropFallback: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=1600&auto=format&fit=crop&q=80',
    trailerUrl: 'https://www.youtube.com/embed/gCcx85zbxz4',
    movieUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    categories: ['scifi', 'action', 'popularMovies', 'topRated']
  },

  {
    id: 'dune-part-two',
    title: 'Desert Destiny: Part II',
    originalTitle: 'Dune: Part Two',
    type: 'movie',
    year: 2026,
    rating: 8.7,
    maturity: '13+',
    duration: '2h 46m',
    badge: 'NEW RELEASE',
    match: '98% Match',
    genre: ['Sci-Fi', 'Action', 'Drama'],
    description: 'Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family.',
    synopsis: 'Facing a choice between the love of his life and the fate of the universe, Paul endeavors to prevent a terrible future only he can foresee.',
    cast: ['Timothée Chalamet', 'Zendaya', 'Rebecca Ferguson'],
    director: 'Denis Villeneuve',
    poster: 'assets/images/dune.jfif',
    backdrop: 'assets/images/tea.avif',
    posterFallback: 'https://images.unsplash.com/photo-1524985069026-dd778a71c7b4?w=600&auto=format&fit=crop&q=80',
    backdropFallback: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=1600&auto=format&fit=crop&q=80',
    trailerUrl: 'https://www.youtube.com/embed/Way9Dexny3w',
    movieUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4',
    categories: ['trending', 'popularMovies', 'scifi', 'newReleases', 'topRated']
  },

  {
    id: 'the-witcher',
    title: 'The Lone Hunter',
    originalTitle: 'The Witcher',
    type: 'tv',
    year: 2025,
    rating: 8.2,
    maturity: '18+',
    duration: '3 Seasons',
    badge: 'FANTASY',
    match: '94% Match',
    genre: ['Fantasy', 'Action', 'Adventure'],
    description: 'Geralt of Rivia, a mutated monster hunter for hire, journeys toward his destiny in a turbulent world.',
    synopsis: 'Where people often prove more wicked than beasts, Geralt discovers that destiny brings three individuals together in the vast Continent.',
    cast: ['Henry Cavill', 'Anya Chalotra', 'Freya Allan'],
    director: 'Lauren Schmidt Hissrich',
    poster: 'assets/images/witcher.jfif',
    backdrop: 'assets/images/AK.jfif',
    posterFallback: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=600&auto=format&fit=crop&q=80',
    backdropFallback: 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=1600&auto=format&fit=crop&q=80',
    trailerUrl: 'https://www.youtube.com/embed/ndl1W4ltcmg',
    movieUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    categories: ['action', 'popularTV']
  },

  {
    id: 'arcane',
    title: 'Hextech Saga',
    originalTitle: 'Arcane',
    type: 'tv',
    year: 2024,
    rating: 9.0,
    maturity: '16+',
    duration: '2 Seasons',
    badge: 'CRITICS PICK',
    match: '99% Match',
    genre: ['Animation', 'Action', 'Sci-Fi'],
    description: 'Set in the utopian region of Piltover and the oppressed underground of Zaun, the story follows the origins of two iconic champions.',
    synopsis: 'Amidst the escalating unrest between the twin cities, two sisters fight on opposite sides of a war between magic and technology.',
    cast: ['Hailee Steinfeld', 'Ella Purnell', 'Kevin Alejandro'],
    director: 'Pascal Charrue',
    poster: 'assets/images/arcane.jfif',
    backdrop: 'assets/images/DelhiC.jfif',
    posterFallback: 'https://images.unsplash.com/photo-1519345182560-3f2917c472ef?w=600&auto=format&fit=crop&q=80',
    backdropFallback: 'https://images.unsplash.com/photo-1493246507139-91e8fad9978e?w=1600&auto=format&fit=crop&q=80',
    trailerUrl: 'https://www.youtube.com/embed/fXm5M__8E7Q',
    movieUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    categories: ['animation', 'action', 'scifi', 'topRated', 'popularTV']
  },

  {
    id: 'delhi-crime',
    title: 'Metropolis Bureau',
    originalTitle: 'Delhi Crime',
    type: 'tv',
    year: 2024,
    rating: 8.5,
    maturity: '18+',
    duration: '2 Seasons',
    badge: 'DRAMA',
    match: '95% Match',
    genre: ['Crime', 'Drama', 'Thriller'],
    description: 'Based on real crime files, a dedicated police team races against time to solve heinous cases in the capital.',
    synopsis: 'Following the investigation by the Delhi Police into notorious crimes, DCP Vartika Chaturvedi leads a tough squad under immense pressure.',
    cast: ['Shefali Shah', 'Rasika Dugal', 'Rajesh Tailang'],
    director: 'Richie Mehta',
    poster: 'assets/images/DelhiC.jfif',
    backdrop: 'assets/images/musafir.jfif',
    posterFallback: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=600&auto=format&fit=crop&q=80',
    backdropFallback: 'https://images.unsplash.com/photo-1514306191717-452ec28c7814?w=1600&auto=format&fit=crop&q=80',
    trailerUrl: 'https://www.youtube.com/embed/jNuKReJ3v8c',
    movieUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
    categories: ['drama', 'thriller', 'popularTV']
  },

  {
    id: 'all-of-us-are-dead',
    title: 'Outbreak Zero',
    originalTitle: 'All of Us Are Dead',
    type: 'tv',
    year: 2025,
    rating: 7.7,
    maturity: '18+',
    duration: '1 Season',
    badge: 'HORROR',
    match: '92% Match',
    genre: ['Horror', 'Action', 'Drama'],
    description: 'A high school becomes ground zero for a zombie virus outbreak. Trapped students must fight their way out.',
    synopsis: 'With no food, water, or help coming, students at Hyosan High School use desk chairs and lockers to defend against ferocious zombies.',
    cast: ['Park Ji-hu', 'Yoon Chan-young', 'Cho Yi-hyun'],
    director: 'Lee JQ',
    poster: 'assets/images/allofus.jfif',
    backdrop: 'assets/images/sinister.jpg',
    posterFallback: 'https://images.unsplash.com/photo-1509281373149-e957c6296406?w=600&auto=format&fit=crop&q=80',
    backdropFallback: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1600&auto=format&fit=crop&q=80',
    trailerUrl: 'https://www.youtube.com/embed/IN5TD4VRcSM',
    movieUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
    categories: ['horror', 'action', 'popularTV', 'trending']
  },

  {
    id: 'the-crown',
    title: 'Royal Legacy',
    originalTitle: 'The Crown',
    type: 'tv',
    year: 2023,
    rating: 8.6,
    maturity: '16+',
    duration: '6 Seasons',
    badge: 'EMMY WINNER',
    match: '96% Match',
    genre: ['Drama', 'History'],
    description: 'Follows the political rivalries and romance of Queen Elizabeth II\'s reign and the events that shaped the second half of the 20th century.',
    synopsis: 'A dramatized record of Queen Elizabeth II\'s personal journey, royal duties, and the changing social landscape across decades.',
    cast: ['Claire Foy', 'Olivia Colman', 'Imelda Staunton'],
    director: 'Peter Morgan',
    poster: 'assets/images/crown.jfif',
    backdrop: 'assets/images/eastpalace.jfif',
    posterFallback: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=600&auto=format&fit=crop&q=80',
    backdropFallback: 'https://images.unsplash.com/photo-1514306191717-452ec28c7814?w=1600&auto=format&fit=crop&q=80',
    trailerUrl: 'https://www.youtube.com/embed/JWtnJjn6ng0',
    movieUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    categories: ['drama', 'popularTV', 'topRated']
  },

  {
    id: 'peaky-blinders',
    title: 'Birmingham Syndicate',
    originalTitle: 'Peaky Blinders',
    type: 'tv',
    year: 2024,
    rating: 8.8,
    maturity: '18+',
    duration: '6 Seasons',
    badge: 'TOP RATED',
    match: '98% Match',
    genre: ['Crime', 'Drama', 'Action'],
    description: 'A gangster family epic set in 1919 Birmingham, England; centered on a gang who sew razor blades in the peaks of their caps.',
    synopsis: 'Thomas Shelby leads the Peaky Blinders gang as they expand their empire beyond gambling into politics and international smuggling.',
    cast: ['Cillian Murphy', 'Paul Anderson', 'Helen McCrory'],
    director: 'Steven Knight',
    poster: 'assets/images/peaky.jfif',
    backdrop: 'assets/images/biker.jfif',
    posterFallback: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=600&auto=format&fit=crop&q=80',
    backdropFallback: 'https://images.unsplash.com/photo-1478760329108-5c3ed9d495a0?w=1600&auto=format&fit=crop&q=80',
    trailerUrl: 'https://www.youtube.com/embed/oVzVdvGIC7U',
    movieUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    categories: ['drama', 'action', 'popularTV', 'topRated']
  },

  {
    id: 'sinister',
    title: 'Shadows in the Dark',
    originalTitle: 'Sinister',
    type: 'movie',
    year: 2024,
    rating: 7.6,
    maturity: '18+',
    duration: '1h 50m',
    badge: 'HORROR',
    match: '89% Match',
    genre: ['Horror', 'Mystery', 'Thriller'],
    description: 'A true-crime writer discovers a box of super 8 home movies in his new house that suggest a terrifying supernatural threat.',
    synopsis: 'Ellison Oswald moves his family into a home where a murder took place, hoping to write a bestseller, but uncovers ancient demonic forces.',
    cast: ['Ethan Hawke', 'Juliet Rylance', 'Fred Thompson'],
    director: 'Scott Derrickson',
    poster: 'assets/images/sinister.jpg',
    backdrop: 'assets/images/sin.jfif',
    posterFallback: 'https://images.unsplash.com/photo-1509281373149-e957c6296406?w=600&auto=format&fit=crop&q=80',
    backdropFallback: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1600&auto=format&fit=crop&q=80',
    trailerUrl: 'https://www.youtube.com/embed/_hand_8fW7E',
    movieUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    categories: ['horror', 'thriller', 'popularMovies']
  },

  {
    id: 'me-before-you',
    title: 'A Promise of Love',
    originalTitle: 'Me Before You',
    type: 'movie',
    year: 2023,
    rating: 7.8,
    maturity: '13+',
    duration: '1h 50m',
    badge: 'ROMANCE',
    match: '93% Match',
    genre: ['Comedy', 'Drama', 'Romance'],
    description: 'A girl in a small town forms an unlikely bond with a recently-paralyzed man she taking care of.',
    synopsis: 'Louisa Clark takes a job caring for Will Traynor, a wealthy young banker left wheelchair-bound. Her cheerful spirit begins to change his outlook on life.',
    cast: ['Emilia Clarke', 'Sam Claflin', 'Janet McTeer'],
    director: 'Thea Sharrock',
    poster: 'assets/images/mebeforeyou.jfif',
    backdrop: 'assets/images/love.jfif',
    posterFallback: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&auto=format&fit=crop&q=80',
    backdropFallback: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1600&auto=format&fit=crop&q=80',
    trailerUrl: 'https://www.youtube.com/embed/Eh993__rOxA',
    movieUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4',
    categories: ['comedy', 'drama', 'popularMovies']
  },

  {
    id: 'spiderman-no-way-home',
    title: 'Spider Hero: Multiverse',
    originalTitle: 'Spider-Man: No Way Home',
    type: 'movie',
    year: 2024,
    rating: 8.3,
    maturity: '13+',
    duration: '2h 28m',
    badge: 'BLOCKBUSTER',
    match: '98% Match',
    genre: ['Action', 'Sci-Fi', 'Family'],
    description: 'With Spider-Man\'s identity revealed, Peter asks Doctor Strange for help, unleashing dangerous multiverse villains.',
    synopsis: 'When a spell goes wrong, dangerous foes from other worlds enter Peter Parker\'s reality, forcing him to discover what being a hero really means.',
    cast: ['Tom Holland', 'Zendaya', 'Benedict Cumberbatch'],
    director: 'Jon Watts',
    poster: 'assets/images/spiderman.jfif',
    backdrop: 'assets/images/movie5.jfif',
    posterFallback: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=600&auto=format&fit=crop&q=80',
    backdropFallback: 'https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?w=1600&auto=format&fit=crop&q=80',
    trailerUrl: 'https://www.youtube.com/embed/JfVOs4VSpmA',
    movieUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    categories: ['action', 'family', 'scifi', 'popularMovies', 'trending']
  },

  {
    id: 'elite',
    title: 'Academy Secrets',
    originalTitle: 'Elite',
    type: 'tv',
    year: 2024,
    rating: 7.5,
    maturity: '18+',
    duration: '7 Seasons',
    badge: 'DRAMA',
    match: '90% Match',
    genre: ['Drama', 'Crime', 'Thriller'],
    description: 'When three working-class teens enroll in an exclusive private school, clash leads to murder.',
    synopsis: 'Tension between wealthy students and new working-class transfer students culminates in secret romantic affairs and a unsolved murder.',
    cast: ['Itzan Escamilla', 'Miguel Bernardeau', 'Arón Piper'],
    director: 'Carlos Montero',
    poster: 'assets/images/elite.jfif',
    backdrop: 'assets/images/movie4.jfif',
    posterFallback: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&auto=format&fit=crop&q=80',
    backdropFallback: 'https://images.unsplash.com/photo-1514306191717-452ec28c7814?w=1600&auto=format&fit=crop&q=80',
    trailerUrl: 'https://www.youtube.com/embed/QNwhAdrdwpw',
    movieUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    categories: ['drama', 'thriller', 'popularTV']
  },

  {
    id: 'you',
    title: 'Obsession',
    originalTitle: 'You',
    type: 'tv',
    year: 2024,
    rating: 7.7,
    maturity: '18+',
    duration: '4 Seasons',
    badge: 'THRILLER',
    match: '92% Match',
    genre: ['Drama', 'Thriller', 'Crime'],
    description: 'A dangerously charming, intensely obsessive young man goes to extreme measures to insert himself into the lives of women.',
    synopsis: 'Bookstore manager Joe Goldberg uses social media and modern technology to track down and manipulate those he becomes obsessed with.',
    cast: ['Penn Badgley', 'Victoria Pedretti', 'Tati Gabrielle'],
    director: 'Greg Berlanti',
    poster: 'assets/images/you.jfif',
    backdrop: 'assets/images/movie6.jfif',
    posterFallback: 'https://images.unsplash.com/photo-1509281373149-e957c6296406?w=600&auto=format&fit=crop&q=80',
    backdropFallback: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1600&auto=format&fit=crop&q=80',
    trailerUrl: 'https://www.youtube.com/embed/ga1mAiX6554',
    movieUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    categories: ['thriller', 'drama', 'popularTV']
  },

  {
    id: 'joker',
    title: 'The Laughing Clown',
    originalTitle: 'Joker',
    type: 'movie',
    year: 2024,
    rating: 8.4,
    maturity: '18+',
    duration: '2h 02m',
    badge: 'ACADEMY AWARD',
    match: '97% Match',
    genre: ['Crime', 'Drama', 'Thriller'],
    description: 'A mentally troubled comedian Arthur Fleck embarks on a downward spiral that leads to the birth of an iconic villain.',
    synopsis: 'Disregarded and mistreated by society, party clown Arthur Fleck descends into a spiral of revolution and bloody crime in Gotham City.',
    cast: ['Joaquin Phoenix', 'Robert De Niro', 'Zazie Beetz'],
    director: 'Todd Phillips',
    poster: 'assets/images/joker1.jfif',
    backdrop: 'assets/images/movie2.jfif',
    posterFallback: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=600&auto=format&fit=crop&q=80',
    backdropFallback: 'https://images.unsplash.com/photo-1478760329108-5c3ed9d495a0?w=1600&auto=format&fit=crop&q=80',
    trailerUrl: 'https://www.youtube.com/embed/zAGVQLHvwOY',
    movieUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    categories: ['drama', 'thriller', 'popularMovies', 'topRated']
  },

  {
    id: 'latent',
    title: 'Latent Mind',
    originalTitle: 'Latent',
    type: 'movie',
    year: 2025,
    rating: 8.0,
    maturity: '16+',
    duration: '1h 45m',
    badge: 'NEW',
    match: '91% Match',
    genre: ['Sci-Fi', 'Thriller'],
    description: 'A scientist unlocks latent human brain capabilities, triggering an unexpected mental connection across time.',
    synopsis: 'In a secret lab trial, Dr. Elena Vance tests a neuro-stimulator that enables telepathic memory sharing with startling consequences.',
    cast: ['Dev Patel', 'Florence Pugh', 'Riz Ahmed'],
    director: 'Alex Garland',
    poster: 'assets/images/latent.jfif',
    backdrop: 'assets/images/bgmain.jpeg',
    posterFallback: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=600&auto=format&fit=crop&q=80',
    backdropFallback: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=1600&auto=format&fit=crop&q=80',
    trailerUrl: 'https://www.youtube.com/embed/EXeTwQWrcwY',
    movieUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    categories: ['scifi', 'thriller', 'newReleases']
  }
];


// ==========================================================================
// Helper Functions for Data Access
// ==========================================================================

function getAllMovies() {
  return moviesData.filter(item => item.type === 'movie');
}

function getAllTVShows() {
  return moviesData.filter(item => item.type === 'tv');
}

function getMovieById(id) {
  return moviesData.find(item => item.id === id);
}

function getMoviesByCategory(category) {
  return moviesData.filter(
    item => item.categories && item.categories.includes(category)
  );
}

function searchData(query) {
  if (!query) return [];

  const q = query.toLowerCase().trim();

  return moviesData.filter(item =>
    item.title.toLowerCase().includes(q) ||
    (item.originalTitle && item.originalTitle.toLowerCase().includes(q)) ||
    item.genre.some(g => g.toLowerCase().includes(q)) ||
    item.cast.some(c => c.toLowerCase().includes(q)) ||
    item.director.toLowerCase().includes(q)
  );
}